services:
  tasks-md:
    image: baldissaramatheus/tasks.md
    container_name: tasks.md
    environment:
      PUID: 1000
      PGID: 1000
      TITLE: authori
      BASE_PATH: ""
      LOCAL_IMAGES_CLEANUP-INTERVAL: 1440
    ports:
      - "8080:8080"
    volumes:
      - .:/tasks/
      - .config/:/config/
    restart: unless-stopped
